### ISSUE TITLE
run dev :  Failed to resolve entry for package "vite-ssr"

### ISSUE THREAD

**Issue by robthepaper** [frandiox/vitesse-ssr-template#15]
Here is the console output :
Can someone help on this?

`yarn run v1.19.0
$ vite-ssr --port 3333 --open

 -- SSR mode

X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-611778e0.js:38290:10:
      38290 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38290:11)
    at resolvePackageEntry (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38286:9)
    at tryNodeResolve (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38093:20)
    at Context.resolveId (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:37901:28)
    at Object.resolveId (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36470:55)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resolve (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36682:26)
    at async D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36839:34
    at async callback (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\esbuild\lib\main.js:921:28)
    at async handleRequest (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\esbuild\lib\main.js:701:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-611778e0.js:36829:18:
      36829 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36829:19)
    at handlePlugins (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\esbuild\lib\main.js:843:23)
    at Object.buildOrServe (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\esbuild\lib\main.js:1137:7)
    at D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\esbuild\lib\main.js:2079:17
    at new Promise (<anonymous>)
    at Object.build (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\esbuild\lib\main.js:2078:14)
    at Object.build (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\esbuild\lib\main.js:1927:51)
    at D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:36630:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/main.ts:3:36:
      3 │ import viteSSR, { ClientOnly } from "vite-ssr";
        ╵                                     ~~~~~~~~~~

Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-611778e0.js:38290:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.

2:33:45 PM [vite] Error when evaluating SSR module D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\src\main.ts:
Error: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38290:11)
    at resolvePackageEntry (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38286:9)
    at tryNodeResolve (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38101:20)
    at viteResolve (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58385:26)
    at nodeImport (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58422:15)
    at ssrImport (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58319:20)
    at eval (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\src\main.ts:8:37)
    at async instantiateModule (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58364:9)
Error: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38290:11)
    at resolvePackageEntry (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38286:9)
    at tryNodeResolve (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38101:20)
    at viteResolve (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58385:26)
    at nodeImport (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58422:15)
    at ssrImport (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58319:20)
    at eval (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\src\main.ts:8:37)
    at async instantiateModule (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58364:9)
2:33:45 PM [vite] Internal server error: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.
      at packageEntryFailure (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38290:11)
      at resolvePackageEntry (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38286:9)
      at tryNodeResolve (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:38101:20)
      at viteResolve (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58385:26)
      at nodeImport (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58422:15)
      at ssrImport (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58319:20)
      at eval (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\src\main.ts:8:37)
      at async instantiateModule (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite\dist\node\chunks\dep-611778e0.js:58364:9)
TypeError: render is not a function
    at handleSsrRequest (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite-ssr\dev\server.js:88:37)
2:33:45 PM [vite] Internal server error: render is not a function
      at handleSsrRequest (D:\@PROJETS_EN_COURS\20200409_Autosite\DEV_NUXT\VITE-FASTIFY\vitesse-ssr-template\node_modules\vite-ssr\dev\server.js:88:37)

`

**Comment by frandiox** [comment]
Hi! This is a known issue with Vite 2.8+. Downgrade to 2.7 or wait until it's fixed in a new release (it's already in a PR waiting to be merged).

**Comment by robthepaper** [comment]
oh ok
thanks!
